# Generated by Django 4.0.4 on 2022-04-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_unique_username_user_unique_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.CharField(max_length=120),
        ),
    ]
