# Generated by Django 4.0.4 on 2022-04-28 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_rating'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='Unique_Password',
        ),
    ]
