# Generated by Django 4.0 on 2022-04-26 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answercomment',
            name='answer',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='answer.answer'),
        ),
    ]
