# Generated by Django 4.0.4 on 2022-04-27 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_password'),
        ('answer', '0002_alter_answercomment_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_value', models.IntegerField(default=0)),
                ('answer', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='answer.answer')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
